name: meetteam
description: "Une application de gestion de réunions professionnelle"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  # flutter_secure_storage: ^9.0.0  # Commentez ce package
  provider: ^6.1.1
  fluttertoast: ^8.2.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

